"""
This file will handle move decisons made by the computer opponent (bot).
"""

import random

#Piece values
piece_score = {'K': 0, 'Q': 9, 'R': 5, 'B': 3, 'N': 3, 'p': 1}
CHECKMATE = 1000
STALEMATE = 0

#Min-Max
DEPTH = 2

#The computer randomly plays a move from the list of valid moves
def findRandomMoves(validMoves):
    move = validMoves[random.randint(0,len(validMoves)-1)]
    piece = ['Q','R','N','B']
    promotion_choice = random.choice(piece)
    
    return move,promotion_choice

def find2plyBestMoves(gs,validMoves):
    #greedy algorithm (move the gives max score)
    turn_multiplier = 1 if gs.whiteToMove else -1
    
    opponentMinMaxScore = CHECKMATE
    bestPlayerMove = None
    random.shuffle(validMoves)
    #move = []
    
    for playerMove in validMoves:
        gs.make_move(playerMove)
        opponentsMoves = gs.all_valid_moves_advanced()
        opponentsMaxScore = -CHECKMATE
        
        if gs.stalemate:
            opponentsMaxScore = STALEMATE
        elif gs.checkmate:
            opponentsMaxScore = -CHECKMATE
        else:
            for opponentsMove in opponentsMoves:
                gs.make_move(opponentsMove)
                gs.all_valid_moves_advanced()
                if gs.checkmate:
                    score = CHECKMATE
                
                elif gs.stalemate:
                    score = STALEMATE
                
                else:
                    score = -turn_multiplier*scoreMaterial(gs.board)
                
                if score > opponentsMaxScore:
                    opponentsMaxScore = score
                    
                gs.undo_move()
                #move.append((playerMove.Get_chessNotation(),score))
        if opponentsMaxScore < opponentMinMaxScore:
            opponentMinMaxScore = opponentsMaxScore
            bestPlayerMove = playerMove
        gs.undo_move()
        choice = 'Q'
    #print(move)
        
    return bestPlayerMove,choice


"""Helper function that calls the min-max algorithm"""

def findBestMove(gs, validMoves):  
    
    global nextMove
    nextMove = None
    findNegaMaxMoves(gs,validMoves,DEPTH,1 if gs.whiteToMove else -1)
    return nextMove,'Q'

"""

Recursively apply Min-Max algorithm to valid move list based on scores generated by scoreMaterial() 
until a fixed depth
"""

def findMinMaxMoves(gs,validMoves,depth,whiteToMove):
    global nextMove
    if depth == 0:
        return scoreMaterial(gs.board)
    
    if whiteToMove:                     #Maximize 'score' for white
        maxScore = -CHECKMATE
        for move in validMoves:
            gs.make_move(move)
            nextMoves = gs.all_valid_moves_advanced()
            score = findMinMaxMoves(gs,nextMoves,depth-1,False)
            if score > maxScore:
                maxScore = score
                
                if depth == DEPTH:
                    nextMove = move
            
            gs.undo_move()
        return maxScore
    
    else:                               #Minimize 'score' for black
        minScore = CHECKMATE
        for move in validMoves:
            gs.make_move(move)
            nextMoves = gs.all_valid_moves_advanced()
            score = findMinMaxMoves(gs,nextMoves,depth-1,True)
            
            if score < minScore:
                minScore = score
                
                if depth == DEPTH:
                    nextMove = move
                    
            gs.undo_move()
        
        return minScore

"""
Negamax Algorithm: Combines min-max implemetation for black and white evaluations 
into a single clean algorithm.
"""
def findNegaMaxMoves(gs,validMoves,depth,turnMultiplier):
    global nextMove
    if depth == 0:
        return turnMultiplier*scoreBoard(gs)
    
    maxScore = -CHECKMATE
    for move in validMoves:
        
        gs.make_move(move)
        nextMoves = gs.all_valid_moves_advanced()
        score = -findNegaMaxMoves(gs,nextMoves,depth-1,-turnMultiplier)
        
        if score > maxScore:
            maxScore = score
            if depth == DEPTH:
                nextMove = move
        gs.undo_move()
    return maxScore
    

#Note: Positive Score is good for white, Negative for black
def scoreBoard(gs):
    if gs.checkmate:
        if gs.whiteToMove:
            score = -CHECKMATE
        
        else:
            score = CHECKMATE
    
    elif gs.stalemate:
        score = STALEMATE
    
    score = 0
        
    for row in gs.board:
        for square in row:
            
            if square[0] == 'w':
                score+= piece_score[square[1]]
            
            elif square[0] == 'b':
                score -= piece_score[square[1]]
    
    return score

"""
Score the board based on the material
(We can plug in other scoring methods to getting the board score later)
"""
def scoreMaterial(board):
    score = 0
    
    for row in board:
        for square in row:
            
            if square[0] == 'w':
                score+= piece_score[square[1]]
            
            elif square[0] == 'b':
                score -= piece_score[square[1]]
    
    return score